"""add investigation reasoning steps

Revision ID: 00fd971bffa1
Revises: 8fd16636667b
Create Date: 2026-08-17 12:03:55.837607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fd971bffa1'
down_revision: Union[str, Sequence[str], None] = '8fd16636667b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_event_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_steps_finding_id'), 'investigation_steps', ['finding_id'], unique=False)
    op.create_index(op.f('ix_investigation_steps_id'), 'investigation_steps', ['id'], unique=False)
    op.create_index(op.f('ix_investigation_steps_step_type'), 'investigation_steps', ['step_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_steps_step_type'), table_name='investigation_steps')
    op.drop_index(op.f('ix_investigation_steps_id'), table_name='investigation_steps')
    op.drop_index(op.f('ix_investigation_steps_finding_id'), table_name='investigation_steps')
    op.drop_table('investigation_steps')
    # ### end Alembic commands ###
