"""add_cyrenix_expansion_models

Revision ID: 4ee69e1e5848
Revises: 0acdfc21f49d
Create Date: 2026-08-28 09:31:11.777626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee69e1e5848'
down_revision: Union[str, Sequence[str], None] = '0acdfc21f49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('risk_score', sa.String(length=20), nullable=False),
    sa.Column('baseline_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_profiles_id'), 'identity_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_identity_profiles_username'), 'identity_profiles', ['username'], unique=True)
    op.create_table('response_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('action_effect', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_policies_id'), 'response_policies', ['id'], unique=False)
    op.create_table('threat_intel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ioc_value', sa.String(length=255), nullable=False),
    sa.Column('ioc_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('reputation', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intel_id'), 'threat_intel', ['id'], unique=False)
    op.create_index(op.f('ix_threat_intel_ioc_type'), 'threat_intel', ['ioc_type'], unique=False)
    op.create_index(op.f('ix_threat_intel_ioc_value'), 'threat_intel', ['ioc_value'], unique=False)
    op.create_table('ai_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('evidence_references', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('model_provider', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_audit_logs_id'), 'ai_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_audit_logs_incident_id'), 'ai_audit_logs', ['incident_id'], unique=False)
    op.create_table('attack_chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_chains_id'), 'attack_chains', ['id'], unique=False)
    op.create_index(op.f('ix_attack_chains_incident_id'), 'attack_chains', ['incident_id'], unique=False)
    op.create_table('identity_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['identity_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_signals_id'), 'identity_signals', ['id'], unique=False)
    op.create_index(op.f('ix_identity_signals_profile_id'), 'identity_signals', ['profile_id'], unique=False)
    op.create_table('attack_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('mitre_tactic', sa.String(length=100), nullable=True),
    sa.Column('mitre_technique', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['attack_chains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_stages_chain_id'), 'attack_stages', ['chain_id'], unique=False)
    op.create_index(op.f('ix_attack_stages_id'), 'attack_stages', ['id'], unique=False)
    op.create_table('investigation_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_needed', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_recommendations_finding_id'), 'investigation_recommendations', ['finding_id'], unique=False)
    op.create_index(op.f('ix_investigation_recommendations_id'), 'investigation_recommendations', ['id'], unique=False)
    op.create_table('correlation_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('source_event_id', sa.Integer(), nullable=False),
    sa.Column('target_event_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['attack_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlation_links_id'), 'correlation_links', ['id'], unique=False)
    op.create_index(op.f('ix_correlation_links_source_event_id'), 'correlation_links', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_correlation_links_stage_id'), 'correlation_links', ['stage_id'], unique=False)
    op.create_index(op.f('ix_correlation_links_target_event_id'), 'correlation_links', ['target_event_id'], unique=False)
    op.create_table('response_policy_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['response_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['response_policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_policy_evaluations_action_id'), 'response_policy_evaluations', ['action_id'], unique=False)
    op.create_index(op.f('ix_response_policy_evaluations_id'), 'response_policy_evaluations', ['id'], unique=False)
    op.add_column('findings', sa.Column('mitre_techniques', sa.JSON(), nullable=True))
    op.add_column('findings', sa.Column('supporting_evidence', sa.JSON(), nullable=True))
    op.add_column('findings', sa.Column('contradicting_evidence', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('asset_criticality', sa.String(length=20), nullable=False, server_default='MEDIUM'))
    op.add_column('incidents', sa.Column('identity_risk', sa.String(length=20), nullable=False, server_default='LOW'))
    op.add_column('incidents', sa.Column('priority', sa.String(length=20), nullable=False, server_default='LOW'))
    op.add_column('incidents', sa.Column('progression_level', sa.String(length=20), nullable=False, server_default='INITIAL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'progression_level')
    op.drop_column('incidents', 'priority')
    op.drop_column('incidents', 'identity_risk')
    op.drop_column('incidents', 'asset_criticality')
    op.drop_column('findings', 'contradicting_evidence')
    op.drop_column('findings', 'supporting_evidence')
    op.drop_column('findings', 'mitre_techniques')
    op.drop_index(op.f('ix_response_policy_evaluations_id'), table_name='response_policy_evaluations')
    op.drop_index(op.f('ix_response_policy_evaluations_action_id'), table_name='response_policy_evaluations')
    op.drop_table('response_policy_evaluations')
    op.drop_index(op.f('ix_correlation_links_target_event_id'), table_name='correlation_links')
    op.drop_index(op.f('ix_correlation_links_stage_id'), table_name='correlation_links')
    op.drop_index(op.f('ix_correlation_links_source_event_id'), table_name='correlation_links')
    op.drop_index(op.f('ix_correlation_links_id'), table_name='correlation_links')
    op.drop_table('correlation_links')
    op.drop_index(op.f('ix_investigation_recommendations_id'), table_name='investigation_recommendations')
    op.drop_index(op.f('ix_investigation_recommendations_finding_id'), table_name='investigation_recommendations')
    op.drop_table('investigation_recommendations')
    op.drop_index(op.f('ix_attack_stages_id'), table_name='attack_stages')
    op.drop_index(op.f('ix_attack_stages_chain_id'), table_name='attack_stages')
    op.drop_table('attack_stages')
    op.drop_index(op.f('ix_identity_signals_profile_id'), table_name='identity_signals')
    op.drop_index(op.f('ix_identity_signals_id'), table_name='identity_signals')
    op.drop_table('identity_signals')
    op.drop_index(op.f('ix_attack_chains_incident_id'), table_name='attack_chains')
    op.drop_index(op.f('ix_attack_chains_id'), table_name='attack_chains')
    op.drop_table('attack_chains')
    op.drop_index(op.f('ix_ai_audit_logs_incident_id'), table_name='ai_audit_logs')
    op.drop_index(op.f('ix_ai_audit_logs_id'), table_name='ai_audit_logs')
    op.drop_table('ai_audit_logs')
    op.drop_index(op.f('ix_threat_intel_ioc_value'), table_name='threat_intel')
    op.drop_index(op.f('ix_threat_intel_ioc_type'), table_name='threat_intel')
    op.drop_index(op.f('ix_threat_intel_id'), table_name='threat_intel')
    op.drop_table('threat_intel')
    op.drop_index(op.f('ix_response_policies_id'), table_name='response_policies')
    op.drop_table('response_policies')
    op.drop_index(op.f('ix_identity_profiles_username'), table_name='identity_profiles')
    op.drop_index(op.f('ix_identity_profiles_id'), table_name='identity_profiles')
    op.drop_table('identity_profiles')
    # ### end Alembic commands ###
