"""add response actions

Revision ID: a4e46e635fad
Revises: 00fd971bffa1
Create Date: 2026-08-17 12:20:00.804366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4e46e635fad'
down_revision: Union[str, Sequence[str], None] = '00fd971bffa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_actions_action_type'), 'response_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_response_actions_finding_id'), 'response_actions', ['finding_id'], unique=False)
    op.create_index(op.f('ix_response_actions_id'), 'response_actions', ['id'], unique=False)
    op.drop_index(op.f('ix_investigation_steps_finding_id'), table_name='investigation_steps')
    op.drop_index(op.f('ix_investigation_steps_id'), table_name='investigation_steps')
    op.drop_index(op.f('ix_investigation_steps_step_type'), table_name='investigation_steps')
    op.drop_table('investigation_steps')
    op.drop_table('finding_evidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_evidence',
    sa.Column('finding_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('finding_evidence_event_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('finding_evidence_finding_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id', 'event_id', name=op.f('finding_evidence_pkey'))
    )
    op.create_table('investigation_steps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('conclusion', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('evidence_event_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('investigation_steps_finding_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('investigation_steps_pkey'))
    )
    op.create_index(op.f('ix_investigation_steps_step_type'), 'investigation_steps', ['step_type'], unique=False)
    op.create_index(op.f('ix_investigation_steps_id'), 'investigation_steps', ['id'], unique=False)
    op.create_index(op.f('ix_investigation_steps_finding_id'), 'investigation_steps', ['finding_id'], unique=False)
    op.drop_index(op.f('ix_response_actions_id'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_finding_id'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_action_type'), table_name='response_actions')
    op.drop_table('response_actions')
    # ### end Alembic commands ###
