"""Add case context and analyst notes

Revision ID: e5e3358f1586
Revises: 4ee69e1e5848
Create Date: 2026-08-28 14:20:09.788854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e3358f1586'
down_revision: Union[str, Sequence[str], None] = '4ee69e1e5848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_notes_id'), 'analyst_notes', ['id'], unique=False)
    op.create_index(op.f('ix_analyst_notes_incident_id'), 'analyst_notes', ['incident_id'], unique=False)
    op.add_column('incidents', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('tags', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'tags')
    op.drop_column('incidents', 'owner_id')
    op.drop_index(op.f('ix_analyst_notes_incident_id'), table_name='analyst_notes')
    op.drop_index(op.f('ix_analyst_notes_id'), table_name='analyst_notes')
    op.drop_table('analyst_notes')
    # ### end Alembic commands ###
