"""add response action execution tracking

Revision ID: f1724f2af968
Revises: ab846af9e90f
Create Date: 2026-08-18 09:25:08.751052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1724f2af968'
down_revision: Union[str, Sequence[str], None] = 'ab846af9e90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'response_actions',
        sa.Column(
            'execution_status',
            sa.String(length=30),
            nullable=False,
            server_default='NOT_EXECUTED'
        )
    )

    op.add_column(
        'response_actions',
        sa.Column(
            'execution_mode',
            sa.String(length=20),
            nullable=True
        )
    )

    op.add_column(
        'response_actions',
        sa.Column(
            'execution_message',
            sa.Text(),
            nullable=True
        )
    )

    op.add_column(
        'response_actions',
        sa.Column(
            'executed_at',
            sa.DateTime(timezone=True),
            nullable=True
        )
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_actions', 'executed_at')
    op.drop_column('response_actions', 'execution_message')
    op.drop_column('response_actions', 'execution_mode')
    op.drop_column('response_actions', 'execution_status')
    # ### end Alembic commands ###
